spring:
  application:
    name: testweb
  datasource:  
      url: jdbc:mysql://192.168.159.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: test
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource 
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #useGlobalDataSourceStat: true
  thymeleaf:
    prefix: classpath:templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html # ;charset=<encoding> is added
      
  mvc: 
     static-path-pattern: /**
#    view:
#      prefix: /WEB-INF/view

  http:
    converters:
      preferred-json-mapper: fastjson
      
#  servlet:
#    multipart: 
#      max-request-size: 100MB #最大请求大小
#      max-file-size: 100MB #最大文件大小

  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: templates/**,static/**
 
  test: 
    muti-datasource: 
      default-dataSource-name: dataSourceTest #默认的数据源名称
      url: jdbc:mysql://192.168.159.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: test
      password: 123456
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
logging:
  config: classpath:config/log4j2.yml
  
server:
  port: 8081
    
